---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 86bf476d95733c88bcfa4b4e3459adaefbef9b1f
    app.quarkus.io/build-timestamp: 2022-06-21 - 06:12:50 +0000
  labels:
    app.kubernetes.io/name: flight-tracker-data-aggregator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: flight-tracker-data-aggregator
spec:
  dockerImageRepository: docker.io/ckongman/flight-tracker-data-aggregator
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 86bf476d95733c88bcfa4b4e3459adaefbef9b1f
    app.quarkus.io/build-timestamp: 2022-06-21 - 06:12:50 +0000
  labels:
    app.kubernetes.io/name: flight-tracker-data-aggregator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: flight-tracker-data-aggregator
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: flight-tracker-data-aggregator
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 86bf476d95733c88bcfa4b4e3459adaefbef9b1f
        app.quarkus.io/build-timestamp: 2022-06-21 - 06:12:50 +0000
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: flight-tracker-data-aggregator
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ckongman/flight-tracker-data-aggregator:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: flight-tracker-data-aggregator
