---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: e5538289e5e50c69e8dfdb9502bfb5e6feeedaaf
    app.quarkus.io/build-timestamp: 2022-06-20 - 10:30:57 +0000
  labels:
    app.kubernetes.io/name: flight-tracker-data-simulator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: flight-tracker-data-simulator
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: flight-tracker-data-simulator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: e5538289e5e50c69e8dfdb9502bfb5e6feeedaaf
    app.quarkus.io/build-timestamp: 2022-06-20 - 10:30:57 +0000
  labels:
    app.kubernetes.io/name: flight-tracker-data-simulator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: flight-tracker-data-simulator
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: flight-tracker-data-simulator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: e5538289e5e50c69e8dfdb9502bfb5e6feeedaaf
    app.quarkus.io/build-timestamp: 2022-06-20 - 10:30:57 +0000
  labels:
    app.kubernetes.io/name: flight-tracker-data-simulator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: flight-tracker-data-simulator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: flight-tracker-data-simulator:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:1.11
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: e5538289e5e50c69e8dfdb9502bfb5e6feeedaaf
    app.quarkus.io/build-timestamp: 2022-06-20 - 10:30:57 +0000
  labels:
    app.kubernetes.io/name: flight-tracker-data-simulator
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: flight-tracker-data-simulator
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: flight-tracker-data-simulator
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: e5538289e5e50c69e8dfdb9502bfb5e6feeedaaf
        app.quarkus.io/build-timestamp: 2022-06-20 - 10:30:57 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: flight-tracker-data-simulator
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/flight-tracker-data-simulator-1.0.0-SNAPSHOT-runner.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/flight-tracker-data-simulator-1.0.0-SNAPSHOT-runner.jar
          image: ckongman/flight-tracker-data-simulator:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: flight-tracker-data-simulator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - flight-tracker-data-simulator
        from:
          kind: ImageStreamTag
          name: flight-tracker-data-simulator:1.0.0-SNAPSHOT
      type: ImageChange
